books = [
    {
        "id": 1,
        "title": "Clean Code: A Handbook of Agile Software Craftsmanship",
        "author": "Robert C. Martin",
        "publisher": "Prentice Hall",
        "published_date": "2008-08-01",
        "page_count": 464,
        "language": "English",
    },
    {
        "id": 2,
        "title": "The Pragmatic Programmer: Your Journey to Mastery",
        "author": "Andrew Hunt and David Thomas",
        "publisher": "Addison-Wesley Professional",
        "published_date": "1999-10-20",
        "page_count": 352,
        "language": "English",
    },
    {
        "id": 3,
        "title": "You Don’t Know JS Yet: Scope & Closures",
        "author": "Kyle Simpson",
        "publisher": "O'Reilly Media",
        "published_date": "2020-01-28",
        "page_count": 143,
        "language": "English",
    },
    {
        "id": 4,
        "title": "Introduction to the Theory of Computation",
        "author": "Michael Sipser",
        "publisher": "Cengage Learning",
        "published_date": "2012-01-27",
        "page_count": 504,
        "language": "English",
    },
    {
        "id": 5,
        "title": "Design Patterns: Elements of Reusable Object-Oriented Software",
        "author": "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
        "publisher": "Addison-Wesley Professional",
        "published_date": "1994-10-31",
        "page_count": 395,
        "language": "English",
    },
]